name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: ["1.21.x", "1.22.x"]
    name:  Go ${{ matrix.go }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Run Tests
        run: go test -race -covermode=atomic -coverprofile=coverage.out

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.3.0
        with:
          file: coverage.out
          token: ${{ secrets.CODECOV_TOKEN }}
        
